### ISSUE TITLE
Website does not work

### ISSUE THREAD

**Issue by rolandschuetz** [pixelastic/meetup-random-user#4]
When I open the site and use the url https://www.meetup.com/de-DE/viennajs/events/fgfprqyzmbhc/ I get an error.

**Comment by pixelastic** [comment]
Sorry about that, meetup.com change their markup some time in the past and I didn't realize. Also, the provider I was using for hosting the lambda function (webtask) seem to no longer work either.

I'm going to archive this repository, I might open it again later if I have the need for such a tool again.
